name: Build Mupen64Plus UWP Core for Xbox

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-xbox-core:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Visual Studio environment
      uses: microsoft/setup-msbuild@v1

    - name: Build Mupen64Plus UWP core
      shell: powershell
      run: |
        $solution = 'path\to\mupen64plus.sln'  # <-- Update this to your actual .sln path
        $configuration = 'Release'
        $platform = 'x64'

        msbuild $solution /p:Configuration=$configuration /p:Platform=$platform /verbosity:minimal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mupen64plus-xbox-core
        path: path\to\built\core.dll  # <-- Update this to your actual build output path
